// code generated by automatic build; do not manually edit
/* --------------------------------------------------------------------------------
Luminance Coefficients

based on CIE 1931 2degree colorimetry.
-------------------------------------------------------------------------------- */

#define luma_coeffs_sRGB_Display_EOTF float3(0.2126390058715103, 0.7151686787677559, 0.07219231536073371)
#define luma_coeffs_sRGB_Display_2_2 float3(0.2126390058715103, 0.7151686787677559, 0.07219231536073371)
#define luma_coeffs_sRGB_Linear float3(0.2126390058715103, 0.7151686787677559, 0.07219231536073371)
#define luma_coeffs_BT_709_Display_2_4 float3(0.2126390058715103, 0.7151686787677559, 0.07219231536073371)
#define luma_coeffs_DCIP3_Display_2_6 float3(0.20949167791273052, 0.7215952541610438, 0.06891306792622581)
#define luma_coeffs_DCIP3_D65_Display_2_6 float3(0.2289745640697487, 0.6917385218365064, 0.079286914093745)
#define luma_coeffs_DCIP3_D60_Display_2_6 float3(0.23755220145768094, 0.6892050784052934, 0.07324272013702567)
#define luma_coeffs_Apple_Display_P3 float3(0.20949167791273052, 0.7215952541610438, 0.06891306792622581)
#define luma_coeffs_Adobe_RGB_1998_Display float3(0.29734497525053605, 0.6273635662554661, 0.07529145849399788)
#define luma_coeffs_BT_2020_Display_OETF float3(0.262700212011267, 0.6779980715188711, 0.05930171646986195)
#define luma_coeffs_BT_2020_Linear float3(0.262700212011267, 0.6779980715188711, 0.05930171646986195)
#define luma_coeffs_DCIP3_Linear float3(0.20949167791273052, 0.7215952541610438, 0.06891306792622581)
#define luma_coeffs_Cinema_Gamut_Canon float3(0.2612613575255548, 0.8696421457549598, -0.13090350328051448)
#define luma_coeffs_FGamut_FLog_Fujifilm float3(0.262700212011267, 0.6779980715188711, 0.05930171646986195)
#define luma_coeffs_FGamut_FLog2_Fujifilm float3(0.262700212011267, 0.6779980715188711, 0.05930171646986195)
#define luma_coeffs_NGamut_Nikon float3(0.262700212011267, 0.6779980715188711, 0.05930171646986195)
#define luma_coeffs_SGamut_Sony float3(0.27097967081349217, 0.7866064112209056, -0.057586082034397613)
#define luma_coeffs_SGamut2_Sony float3(0.27097967081349217, 0.7866064112209056, -0.057586082034397613)
#define luma_coeffs_SGamut3_Sony float3(0.27097967081349217, 0.7866064112209056, -0.057586082034397613)
#define luma_coeffs_SGamut3_Cine_Sony float3(0.2150758201155875, 0.8850685017437283, -0.10014432185931582)
#define luma_coeffs_VGamut_Panasonic float3(0.26068555009037364, 0.7748944633296591, -0.03558001342003292)

float3 getLumaCoefficientFromId(int colorspace_id){
    /*
        Retrieve luminance coefficients for the given colorspace.
    */
    // ignored: colorspaceid_Passthrough
    if (colorspace_id == colorspaceid_sRGB_Display_EOTF){
        return luma_coeffs_sRGB_Display_EOTF;
    }
    if (colorspace_id == colorspaceid_sRGB_Display_2_2){
        return luma_coeffs_sRGB_Display_2_2;
    }
    if (colorspace_id == colorspaceid_sRGB_Linear){
        return luma_coeffs_sRGB_Linear;
    }
    if (colorspace_id == colorspaceid_BT_709_Display_2_4){
        return luma_coeffs_BT_709_Display_2_4;
    }
    if (colorspace_id == colorspaceid_DCIP3_Display_2_6){
        return luma_coeffs_DCIP3_Display_2_6;
    }
    if (colorspace_id == colorspaceid_DCIP3_D65_Display_2_6){
        return luma_coeffs_DCIP3_D65_Display_2_6;
    }
    if (colorspace_id == colorspaceid_DCIP3_D60_Display_2_6){
        return luma_coeffs_DCIP3_D60_Display_2_6;
    }
    if (colorspace_id == colorspaceid_Apple_Display_P3){
        return luma_coeffs_Apple_Display_P3;
    }
    if (colorspace_id == colorspaceid_Adobe_RGB_1998_Display){
        return luma_coeffs_Adobe_RGB_1998_Display;
    }
    if (colorspace_id == colorspaceid_BT_2020_Display_OETF){
        return luma_coeffs_BT_2020_Display_OETF;
    }
    if (colorspace_id == colorspaceid_BT_2020_Linear){
        return luma_coeffs_BT_2020_Linear;
    }
    if (colorspace_id == colorspaceid_DCIP3_Linear){
        return luma_coeffs_DCIP3_Linear;
    }
    if (colorspace_id == colorspaceid_Cinema_Gamut_Canon){
        return luma_coeffs_Cinema_Gamut_Canon;
    }
    if (colorspace_id == colorspaceid_FGamut_FLog_Fujifilm){
        return luma_coeffs_FGamut_FLog_Fujifilm;
    }
    if (colorspace_id == colorspaceid_FGamut_FLog2_Fujifilm){
        return luma_coeffs_FGamut_FLog2_Fujifilm;
    }
    if (colorspace_id == colorspaceid_NGamut_Nikon){
        return luma_coeffs_NGamut_Nikon;
    }
    if (colorspace_id == colorspaceid_SGamut_Sony){
        return luma_coeffs_SGamut_Sony;
    }
    if (colorspace_id == colorspaceid_SGamut2_Sony){
        return luma_coeffs_SGamut2_Sony;
    }
    if (colorspace_id == colorspaceid_SGamut3_Sony){
        return luma_coeffs_SGamut3_Sony;
    }
    if (colorspace_id == colorspaceid_SGamut3_Cine_Sony){
        return luma_coeffs_SGamut3_Cine_Sony;
    }
    if (colorspace_id == colorspaceid_VGamut_Panasonic){
        return luma_coeffs_VGamut_Panasonic;
    }
    return float3(1.0, 1.0, 1.0);
}
