[project]
name = "AgXc"
version = "1.0.0"
description = "Fork of Troy.S AgX, a display rendering transform available via OCIO and more."
readme = "README.md"
authors = [
    { name = "Liam Collod", email = "monsieurlixm@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "colour-science==0.4.3",
    "numpy==1.22",
    "opencolorio>=2.1",
]

[dependency-groups]
dev = [
    "black>=25",
    "pytest>=8",
    "types-nuke>=13",
    "hatchling",
]

[tool.hatch.build.targets.wheel]
packages = [
    "python/AgXLib",
    ".dev/implementations/obs/python/obs_codegen",
]

[tool.hatch.build.targets.wheel.force-include]
".dev/implementations/ocio/python/giting.py" = "giting.py"
".dev/implementations/ocio/python/ocio_config_helpers.py" = "ocio_config_helpers.py"
".dev/implementations/ocio/python/ocio_matrix_generation.py" = "ocio_matrix_generation.py"
".dev/implementations/ocio/python/ocio_AgXc_config.py" = "ocio_AgXc_config.py"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"