[project]
name = "AgXc"
version = "1.0.0"
description = "Fork of Troy.S AgX, a display rendering transform available via OCIO and more."
readme = "README.md"
authors = [
    { name = "Liam Collod", email = "monsieurlixm@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "colour-science==0.4.3",
    "numpy==1.22",
    "opencolorio>=2.1",
    "openimageio>=3.0.3",
]

[dependency-groups]
dev = [
    "black>=25",
    "pytest>=8",
    "types-nuke>=13",
    "hatchling",
]

[tool.hatch.build.targets.wheel]
packages = [
    "python/AgXLib",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
