[project]
name = "AgXc"
version = "1.0.0"
description = "Fork of Troy.S AgX, a display rendering transform available via OCIO and more."
readme = "README.md"
authors = [
    { name = "Liam Collod", email = "monsieurlixm@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "colour-science==0.4.3",
    "numpy==1.22",
    "opencolorio>=2.1",
]

[dependency-groups]
dev = [
    "black>=25",
    "pytest>=8",
    "types-nuke>=13",
]

[tool.setuptools.packages.find]
where = [
    "python",
    ".dev/implementations/obs/python",
    ".dev/implementations/ocio/modules",
]
include = [
    "AgXLib",
    "obs_codegen",
    "giting",
    "ocio_config_helpers",
    "ocio_matrix_generation",
]
namespaces = false

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"