// code generated by automatic build; do not manually edit
/* --------------------------------------------------------------------------------
Colorspaces
-------------------------------------------------------------------------------- */

struct Colorspace{
    int gamut_id;
    int whitepoint_id;
    int cctf_id;
};

uniform int colorspaceid_Passthrough = 0;
uniform int colorspaceid_sRGB_Display_EOTF = 1;
uniform int colorspaceid_sRGB_Display_2_2 = 2;
uniform int colorspaceid_sRGB_Linear = 3;
uniform int colorspaceid_BT_709_Display_2_4 = 4;
uniform int colorspaceid_DCIP3_Display_2_6 = 5;
uniform int colorspaceid_DCIP3_D65_Display_2_6 = 6;
uniform int colorspaceid_DCIP3_D60_Display_2_6 = 7;
uniform int colorspaceid_Apple_Display_P3 = 8;
uniform int colorspaceid_Adobe_RGB_1998_Display = 9;
uniform int colorspaceid_BT_2020_Display_OETF = 10;
uniform int colorspaceid_BT_2020_Linear = 11;
uniform int colorspaceid_DCIP3_Linear = 12;
uniform int colorspaceid_Cinema_Gamut_Canon = 13;
uniform int colorspaceid_FGamut_FLog_Fujifilm = 14;
uniform int colorspaceid_FGamut_FLog2_Fujifilm = 15;
uniform int colorspaceid_NGamut_Nikon = 16;
uniform int colorspaceid_SGamut_Sony = 17;
uniform int colorspaceid_SGamut2_Sony = 18;
uniform int colorspaceid_SGamut3_Sony = 19;
uniform int colorspaceid_SGamut3_Cine_Sony = 20;
uniform int colorspaceid_VGamut_Panasonic = 21;

Colorspace getColorspaceFromId(int colorspace_id){

    Colorspace colorspace;

    if (colorspace_id == colorspaceid_Passthrough){
        colorspace.gamut_id = -1;
        colorspace.whitepoint_id = -1;
        colorspace.cctf_id = -1;
    };
    if (colorspace_id == colorspaceid_sRGB_Display_EOTF){
        colorspace.gamut_id = gamutid_sRGB;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_sRGB_EOTF;
    };
    if (colorspace_id == colorspaceid_sRGB_Display_2_2){
        colorspace.gamut_id = gamutid_sRGB;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_Power_2_2;
    };
    if (colorspace_id == colorspaceid_sRGB_Linear){
        colorspace.gamut_id = gamutid_sRGB;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = -1;
    };
    if (colorspace_id == colorspaceid_BT_709_Display_2_4){
        colorspace.gamut_id = gamutid_sRGB;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_BT_709;
    };
    if (colorspace_id == colorspaceid_DCIP3_Display_2_6){
        colorspace.gamut_id = gamutid_DCIP3;
        colorspace.whitepoint_id = whitepointid_DCIP3;
        colorspace.cctf_id = cctf_id_DCIP3;
    };
    if (colorspace_id == colorspaceid_DCIP3_D65_Display_2_6){
        colorspace.gamut_id = gamutid_DCIP3;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_DCIP3;
    };
    if (colorspace_id == colorspaceid_DCIP3_D60_Display_2_6){
        colorspace.gamut_id = gamutid_DCIP3;
        colorspace.whitepoint_id = whitepointid_D60;
        colorspace.cctf_id = cctf_id_DCIP3;
    };
    if (colorspace_id == colorspaceid_Apple_Display_P3){
        colorspace.gamut_id = gamutid_Display_P3;
        colorspace.whitepoint_id = whitepointid_DCIP3;
        colorspace.cctf_id = cctf_id_Display_P3;
    };
    if (colorspace_id == colorspaceid_Adobe_RGB_1998_Display){
        colorspace.gamut_id = gamutid_Adobe_RGB_1998;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_Adobe_RGB_1998;
    };
    if (colorspace_id == colorspaceid_BT_2020_Display_OETF){
        colorspace.gamut_id = gamutid_ITUR_BT_2020;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_BT_2020;
    };
    if (colorspace_id == colorspaceid_BT_2020_Linear){
        colorspace.gamut_id = gamutid_ITUR_BT_2020;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = -1;
    };
    if (colorspace_id == colorspaceid_DCIP3_Linear){
        colorspace.gamut_id = gamutid_DCIP3;
        colorspace.whitepoint_id = whitepointid_DCIP3;
        colorspace.cctf_id = -1;
    };
    if (colorspace_id == colorspaceid_Cinema_Gamut_Canon){
        colorspace.gamut_id = gamutid_Cinema_Gamut;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = -1;
    };
    if (colorspace_id == colorspaceid_FGamut_FLog_Fujifilm){
        colorspace.gamut_id = gamutid_ITUR_BT_2020;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_FLog;
    };
    if (colorspace_id == colorspaceid_FGamut_FLog2_Fujifilm){
        colorspace.gamut_id = gamutid_ITUR_BT_2020;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_FLog2;
    };
    if (colorspace_id == colorspaceid_NGamut_Nikon){
        colorspace.gamut_id = gamutid_ITUR_BT_2020;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_NLog;
    };
    if (colorspace_id == colorspaceid_SGamut_Sony){
        colorspace.gamut_id = gamutid_SGamut;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_SLog;
    };
    if (colorspace_id == colorspaceid_SGamut2_Sony){
        colorspace.gamut_id = gamutid_SGamut;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_SLog2;
    };
    if (colorspace_id == colorspaceid_SGamut3_Sony){
        colorspace.gamut_id = gamutid_SGamut;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_SLog3;
    };
    if (colorspace_id == colorspaceid_SGamut3_Cine_Sony){
        colorspace.gamut_id = gamutid_SGamut3_Cine;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_SLog3;
    };
    if (colorspace_id == colorspaceid_VGamut_Panasonic){
        colorspace.gamut_id = gamutid_VGamut;
        colorspace.whitepoint_id = whitepointid_D65;
        colorspace.cctf_id = cctf_id_VLog;
    };
    return colorspace;
}